In [2]:
import numpy as np


In [3]:
n1=np.array([1,2,3,4,5])

In [4]:
n2=np.array([4,5,6,7])

In [9]:
n3=np.intersect1d(n1,n2)

In [11]:
n3

array([4, 5])

In [12]:
n4=np.setdiff1d(n1,n2)

In [13]:
n4

array([1, 2, 3])

In [14]:
# sum of lists ,axis=0 means column sum,axis=1 means row sum
p1=np.array([5,6,7])

In [15]:
p2=np.array([1,2,3])

In [19]:
np.sum([p1,p2])

24

In [23]:
np.sum([p1,p2],axis=0)

array([ 6,  8, 10])

In [24]:
np.sum([p1,p2],axis=1)

array([18,  6])

In [25]:
p5=p1+1

In [26]:
p5

array([6, 7, 8])

In [27]:
p6=p1-1

In [28]:
p6

array([4, 5, 6])

In [29]:
p1*2

array([10, 12, 14])